document.addEventListener('DOMContentLoaded',()=>{
  const dictionary={
    'Đi đến nội dung':'Skip to content','Trang chủ Huỳnh Công Phúc':'Huynh Cong Phuc home','Mở menu':'Open menu','Điều hướng chính':'Main navigation',
    'Giới thiệu':'About','Chuyên môn':'Expertise','Hành trình':'Journey','Dấu ấn':'Highlights','Kỷ niệm':'Memories','Liên hệ':'Contact',
    'Xây dựng hệ thống':'Building reliable','tin cậy':'systems','bằng kỹ thuật và công nghệ.':'through engineering and technology.',
    'Tôi kết nối kiến thức hệ thống điện, tự động hóa và phát triển phần mềm để tạo ra những giải pháp thiết thực cho công việc kỹ thuật.':'I connect power systems, automation, and software engineering to create practical solutions for technical work.',
    'Khám phá chuyên môn':'Explore expertise','Trao đổi':'Get in touch','TP. Hồ Chí Minh':'Ho Chi Minh City','8+ năm kinh nghiệm':'8+ years of experience','Kỹ sư ASEAN':'ASEAN Engineer',
    '01 · GIỚI THIỆU':'01 · ABOUT','Kỹ thuật vững vàng.':'Sound engineering.','Giải pháp rõ ràng.':'Clear solutions.',
    'Tôi là kỹ sư làm việc tại giao điểm của hệ thống điện, tự động hóa và công nghệ thông tin.':'I am an engineer working at the intersection of power systems, automation, and information technology.',
    'Trọng tâm công việc là nâng cao độ tin cậy, hỗ trợ đội ngũ kỹ thuật và chuyển các nhu cầu vận hành phức tạp thành công cụ dễ sử dụng. Bên cạnh công việc chuyên môn, tôi quan tâm đến lưới điện thông minh, năng lượng phân tán và chuyển đổi số.':'My work focuses on improving reliability, supporting engineering teams, and turning complex operational needs into usable tools. I am also interested in smart grids, distributed energy, and digital transformation.',
    'Tin cậy':'Reliability','Hợp tác':'Collaboration','Đổi mới':'Innovation','02 · CHUYÊN MÔN':'02 · EXPERTISE','Năng lực cốt lõi':'Core capabilities',
    'Hệ thống điện':'Power systems','Kinh nghiệm với nền tảng giám sát, quản lý lưới phân phối và các bài toán nâng cao độ tin cậy cung cấp điện.':'Experience with monitoring platforms, distribution management, and initiatives that improve supply reliability.',
    'Tự động hóa':'Automation','Thiết kế quy trình và công cụ hỗ trợ kỹ thuật theo hướng an toàn, nhất quán và dễ bảo trì.':'Designing safe, consistent, and maintainable engineering workflows and tools.',
    'Giải pháp số':'Digital solutions','Phát triển ứng dụng, tích hợp dữ liệu và báo cáo giúp giảm thao tác lặp lại, tăng khả năng phối hợp.':'Developing applications, data integrations, and reports that reduce repetitive work and improve collaboration.',
    'Nghiên cứu ứng dụng':'Applied research','Nghiên cứu lưới điện thông minh, nguồn năng lượng phân tán, lưu trữ năng lượng và mô hình vận hành mới.':'Researching smart grids, distributed energy resources, energy storage, and emerging operating models.',
    '03 · HÀNH TRÌNH':'03 · JOURNEY','Kinh nghiệm & học tập':'Experience & education','HIỆN TẠI':'PRESENT','Kỹ sư hệ thống điện & tự động hóa':'Power Systems & Automation Engineer',
    'Tham gia phát triển, vận hành và cải tiến các giải pháp hỗ trợ độ tin cậy của hệ thống điện.':'Contributing to the development, operation, and improvement of solutions that support power-system reliability.',
    'Được công nhận bởi Liên đoàn các Tổ chức Kỹ sư ASEAN.':'Recognized by the ASEAN Federation of Engineering Organisations.',
    'Điện – Điện tử & Công nghệ thông tin':'Electrical Engineering & Information Technology','Hoàn thành chương trình sau đại học ngành kỹ thuật điện và văn bằng công nghệ thông tin.':'Completed postgraduate studies in electrical engineering and a degree in information technology.',
    'KHỞI ĐẦU':'FOUNDATION','Kỹ thuật điều khiển & tự động hóa':'Control & Automation Engineering','Xây dựng nền tảng chuyên môn qua đào tạo kỹ thuật và kinh nghiệm trong môi trường công nghiệp.':'Built a strong technical foundation through engineering education and industrial experience.',
    '04 · DẤU ẤN':'04 · HIGHLIGHTS','Học tập, ghi nhận và sẻ chia':'Learning, recognition, and contribution','Học tập liên ngành':'Interdisciplinary learning','Đổi mới & ghi nhận':'Innovation & recognition',
    '05 · KẾT NỐI':'05 · CONNECT','Cùng trao đổi những ý tưởng có giá trị.':'Let’s exchange ideas that create value.','Gửi email':'Send an email',
    'Về trang chính':'Back to home','THƯ VIỆN HÌNH ẢNH':'PHOTO GALLERY','Những khoảnh khắc':'Memorable','đáng nhớ.':'moments.','Hành trình học tập, trải nghiệm nghề nghiệp và những dấu mốc được lưu lại qua hình ảnh.':'A visual record of learning, professional experiences, and meaningful milestones.',
    'Một dấu mốc nghề nghiệp đáng tự hào.':'A proud professional milestone.','Học tập':'Education','Công nghệ thông tin':'Information Technology','Mở rộng góc nhìn liên ngành.':'Broadening an interdisciplinary perspective.','Ghi nhận':'Recognition','Giá trị đến từ những cải tiến thiết thực.':'Value created through practical improvements.','Chân dung':'Portrait','Không ngừng học hỏi và kiến tạo giá trị.':'Always learning and creating value.','Dấu ấn cá nhân':'Personal identity','Nghiên cứu · Kiến tạo · Phụng sự':'Research · Create · Serve',
    'KHO ẢNH KỶ NIỆM':'MEMORY ARCHIVE','Hành trình qua những khung hình.':'A journey through photographs.','Những hình ảnh an toàn đã được chọn lọc từ thư mục Picture.':'A curated collection of safe photographs from the Picture archive.','Khoảnh khắc':'Moment','Những khoảnh khắc đáng nhớ':'Memorable moments','Về đầu trang':'Back to top'
  };
  const originals=new WeakMap();
  const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT,{acceptNode:n=>n.parentElement&&['SCRIPT','STYLE'].includes(n.parentElement.tagName)?NodeFilter.FILTER_REJECT:NodeFilter.FILTER_ACCEPT});
  const nodes=[];while(walker.nextNode()){const node=walker.currentNode;if(node.nodeValue.trim()){originals.set(node,node.nodeValue);nodes.push(node);}}
  const attributes=['aria-label','alt','content'];
  document.querySelectorAll('[aria-label],[alt],meta[name="description"],meta[property="og:title"],meta[property="og:description"]').forEach(el=>attributes.forEach(attr=>{if(el.hasAttribute(attr))el.dataset['original'+attr.replace('-','')]=el.getAttribute(attr);}));
  function translated(value){const lead=value.match(/^\s*/)[0],trail=value.match(/\s*$/)[0],core=value.trim();if(dictionary[core])return lead+dictionary[core]+trail;const moment=core.match(/^Khoảnh khắc\s+(\d+)$/);if(moment)return lead+'Moment '+moment[1]+trail;return value;}
  function applyLanguage(lang){document.documentElement.lang=lang;nodes.forEach(node=>{const original=originals.get(node);node.nodeValue=lang==='en'?translated(original):original;});document.querySelectorAll('[aria-label],[alt],meta[name="description"],meta[property="og:title"],meta[property="og:description"]').forEach(el=>attributes.forEach(attr=>{const key='original'+attr.replace('-','');const original=el.dataset[key];if(original!==undefined)el.setAttribute(attr,lang==='en'?(dictionary[original]||original):original);}));const onMemories=location.pathname.endsWith('memories.html');document.title=lang==='en'?(onMemories?'Memories | Huynh Cong Phuc':'Huynh Cong Phuc | Power Systems & Automation'):(onMemories?'Kỷ niệm | Huỳnh Công Phúc':'Huỳnh Công Phúc | Power Systems & Automation');document.querySelectorAll('[data-language-toggle] span').forEach(span=>span.textContent=lang==='en'?'Tiếng Việt':'English');localStorage.setItem('site-language',lang);}
  document.querySelectorAll('[data-language-toggle]').forEach(button=>button.addEventListener('click',()=>applyLanguage(document.documentElement.lang==='en'?'vi':'en')));
  applyLanguage(localStorage.getItem('site-language')==='en'?'en':'vi');
});

