document.addEventListener('DOMContentLoaded',()=>{
 const RAW_URL='https://raw.githubusercontent.com/huynhcongphuc/huynhcongphuc.github.io/main/data/tech-news.json',grid=document.querySelector('.news-grid'),filters=[...document.querySelectorAll('[data-news-filter]')],search=document.getElementById('news-search'),empty=document.getElementById('news-empty'),note=document.querySelector('.news-note');let cards=[...document.querySelectorAll('[data-news-card]')],category='all',feed=null;
 const lang=()=>String(document.documentElement.lang||'vi').toLowerCase().startsWith('en')?'en':'vi';
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const sourceClass=s=>String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'news';
 const labelForTag=(tag,l)=>({power:{vi:'HỆ THỐNG ĐIỆN',en:'POWER SYSTEM'},scada:{vi:'SCADA',en:'SCADA'},derms:{vi:'DERMS / DER',en:'DERMS / DER'}}[tag]?.[l]||String(tag||'').toUpperCase());
 const regionLabel=(region,l)=>region==='vietnam'?(l==='en'?'VIETNAM':'VIỆT NAM'):(l==='en'?'INTERNATIONAL':'QUỐC TẾ');
 const apply=()=>{const q=(search?.value||'').trim().toLowerCase();let shown=0;cards.forEach(card=>{const tags=(card.dataset.tags||'').split(',').filter(Boolean),text=card.textContent.toLowerCase(),show=(category==='all'||tags.includes(category))&&(!q||text.includes(q));card.hidden=!show;if(show)shown++;});if(empty)empty.style.display=shown?'none':'block';};
 const syncNav=(l)=>{const labels={'index.html#about':l==='en'?'About':'Giới thiệu','memories.html':l==='en'?'Memories':'Kỷ niệm','products.html':l==='en'?'Technology Products':'Sản phẩm công nghệ','research.html':l==='en'?'Research':'Bài nghiên cứu','news.html':l==='en'?'Technology News':'Tin tức công nghệ','stats.html':l==='en'?'Statistics':'Thống kê'};Object.entries(labels).forEach(([href,text])=>{const a=document.querySelector(`#site-nav a[href="${href}"]`);if(a)a.textContent=text;});const contact=document.querySelector('#site-nav .nav-cta');if(contact){const icon=contact.querySelector('svg,i');contact.textContent=l==='en'?' Contact':' Liên hệ';if(icon)contact.prepend(icon);}};
 const syncText=()=>{const l=lang();document.querySelectorAll('[data-vi][data-en]').forEach(el=>el.textContent=el.dataset[l]);syncNav(l);if(search){search.placeholder=l==='en'?'Search power system, SCADA, DERMS…':'Tìm hệ thống điện, SCADA, DERMS…';search.setAttribute('aria-label',l==='en'?'Search articles':'Tìm bài viết');}document.title=l==='en'?'Power System News | Huynh Cong Phuc':'Tin tức hệ thống điện | Huỳnh Công Phúc';cards.forEach(card=>{const region=card.dataset.region,tag=(card.dataset.primaryTag||'power');const badge=card.querySelector('.news-tag');if(badge&&region)badge.textContent=`${regionLabel(region,l)} · ${labelForTag(tag,l)}`;const read=card.querySelector('.news-link span');if(read)read.textContent=l==='en'?'Read original':'Đọc bài gốc';});const status=document.getElementById('news-feed-status');if(status&&feed){const updated=feed.updated_at?new Date(feed.updated_at).toLocaleString(l==='en'?'en-US':'vi-VN'):'';const total=Array.isArray(feed.items)?feed.items.length:0;const intl=feed.items?.filter(x=>x.region!=='vietnam').length||0;const vn=feed.items?.filter(x=>x.region==='vietnam').length||0;status.textContent=l==='en'?`${total} recent articles (${intl} international + ${vn} Vietnam) · Power System / SCADA / DERMS · max age 3 months${updated?` · Updated ${updated}`:''}`:`${total} bài mới (${intl} quốc tế + ${vn} Việt Nam) · Hệ thống điện / SCADA / DERMS · không quá 3 tháng${updated?` · Cập nhật ${updated}`:''}`;}apply();};
 function renderFeed(data){if(!grid||!Array.isArray(data?.items)||!data.items.length)return false;feed=data;grid.innerHTML=data.items.slice(0,20).map(item=>{const tags=Array.isArray(item.tags)&&item.tags.length?item.tags:['power'],summary=item.summary||'',image=item.image||'',src=item.source||'Source',primary=tags[0],region=item.region==='vietnam'?'vietnam':'international';return `<article class="news-card news-card-live source-${sourceClass(src)}" data-news-card data-region="${region}" data-primary-tag="${esc(primary)}" data-tags="${esc(tags.join(','))}">${image?`<figure class="news-image"><img src="${esc(image)}" alt="" loading="lazy" referrerpolicy="no-referrer"></figure>`:''}<div class="news-card-top"><div class="news-icon"><i data-lucide="${esc(item.icon||'zap')}"></i></div><span class="news-source">${esc(src)}</span></div><span class="news-tag"></span><h2>${esc(item.title)}</h2>${summary?`<p>${esc(summary)}</p>`:''}<div class="news-meta">${item.published_label?`<span>${esc(item.published_label)}</span>`:''}<span>${esc(src)}</span></div><a class="news-link" href="${esc(item.url)}" target="_blank" rel="noopener noreferrer"><span></span><i data-lucide="arrow-up-right"></i></a></article>`;}).join('');cards=[...grid.querySelectorAll('[data-news-card]')];if(note&&!document.getElementById('news-feed-status')){const s=document.createElement('p');s.id='news-feed-status';s.className='news-feed-status';note.before(s);}if(window.lucide)window.lucide.createIcons();syncText();return true;}
 async function loadFeed(){for(const url of [`${RAW_URL}?t=${Date.now()}`,`data/tech-news.json?t=${Date.now()}`]){try{const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);if(renderFeed(await r.json()))return;}catch(e){console.warn('Power news feed unavailable:',url,e);}}apply();}
 filters.forEach(btn=>btn.addEventListener('click',()=>{filters.forEach(x=>x.classList.remove('active'));btn.classList.add('active');category=btn.dataset.newsFilter||'all';apply();}));search?.addEventListener('input',apply);new MutationObserver(m=>{if(m.some(x=>x.type==='attributes'&&x.attributeName==='lang'))syncText();}).observe(document.documentElement,{attributes:true});syncText();loadFeed();setInterval(loadFeed,30*60*1000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)loadFeed();});
});