document.addEventListener('DOMContentLoaded',()=>{
 const RAW_URL='https://raw.githubusercontent.com/huynhcongphuc/huynhcongphuc.github.io/main/data/tech-news.json',grid=document.querySelector('.news-grid'),filters=[...document.querySelectorAll('[data-news-filter]')],search=document.getElementById('news-search'),empty=document.getElementById('news-empty'),note=document.querySelector('.news-note');let cards=[...document.querySelectorAll('[data-news-card]')],category='all',feed=null;
 const lang=()=>String(document.documentElement.lang||'vi').toLowerCase().startsWith('en')?'en':'vi';
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const sourceClass=s=>String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'news';
 const apply=()=>{const q=(search?.value||'').trim().toLowerCase();let shown=0;cards.forEach(card=>{const tags=(card.dataset.tags||'').split(',').filter(Boolean),text=card.textContent.toLowerCase(),show=(category==='all'||tags.includes(category))&&(!q||text.includes(q));card.hidden=!show;if(show)shown++;});if(empty)empty.style.display=shown?'none':'block';};
 const syncText=()=>{const l=lang();document.querySelectorAll('[data-vi][data-en]').forEach(el=>el.textContent=el.dataset[l]);if(search)search.placeholder=l==='en'?'Search power system, SCADA, DERMS…':'Tìm hệ thống điện, SCADA, DERMS…';const status=document.getElementById('news-feed-status');if(status&&feed){const updated=feed.updated_at?new Date(feed.updated_at).toLocaleString(l==='en'?'en-US':'vi-VN'):'';status.textContent=l==='en'?`20 focused articles: 10 international + 10 Vietnam · Power System / SCADA / DERMS${updated?` · Updated ${updated}`:''}`:`20 bài chuyên ngành: 10 quốc tế + 10 Việt Nam · Hệ thống điện / SCADA / DERMS${updated?` · Cập nhật ${updated}`:''}`;}apply();};
 function renderFeed(data){if(!grid||!Array.isArray(data?.items)||!data.items.length)return false;feed=data;grid.innerHTML=data.items.slice(0,20).map((item,i)=>{const tags=Array.isArray(item.tags)&&item.tags.length?item.tags:['power'],summary=item.summary||'',image=item.image||'',src=item.source||'Source',region=item.region==='vietnam'?'VIỆT NAM':'INTERNATIONAL';return `<article class="news-card news-card-live source-${sourceClass(src)}" data-news-card data-tags="${esc(tags.join(','))}">${image?`<figure class="news-image"><img src="${esc(image)}" alt="" loading="lazy" referrerpolicy="no-referrer"></figure>`:''}<div class="news-card-top"><div class="news-icon"><i data-lucide="${esc(item.icon||'zap')}"></i></div><span class="news-source">${esc(src)}</span></div><span class="news-tag">${region} · ${esc(tags[0].toUpperCase())}</span><h2>${esc(item.title)}</h2>${summary?`<p>${esc(summary)}</p>`:''}<div class="news-meta">${item.published_label?`<span>${esc(item.published_label)}</span>`:''}<span>${esc(src)}</span></div><a class="news-link" href="${esc(item.url)}" target="_blank" rel="noopener noreferrer"><span data-vi="Đọc bài gốc" data-en="Read original">Đọc bài gốc</span><i data-lucide="arrow-up-right"></i></a></article>`;}).join('');cards=[...grid.querySelectorAll('[data-news-card]')];if(note&&!document.getElementById('news-feed-status')){const s=document.createElement('p');s.id='news-feed-status';s.className='news-feed-status';note.before(s);}if(window.lucide)window.lucide.createIcons();syncText();return true;}
 async function loadFeed(){for(const url of [`${RAW_URL}?t=${Date.now()}`,`data/tech-news.json?t=${Date.now()}`]){try{const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);if(renderFeed(await r.json()))return;}catch(e){console.warn('Power news feed unavailable:',url,e);}}apply();}
 filters.forEach(btn=>btn.addEventListener('click',()=>{filters.forEach(x=>x.classList.remove('active'));btn.classList.add('active');category=btn.dataset.newsFilter||'all';apply();}));search?.addEventListener('input',apply);new MutationObserver(m=>{if(m.some(x=>x.type==='attributes'&&x.attributeName==='lang'))syncText();}).observe(document.documentElement,{attributes:true});syncText();loadFeed();setInterval(loadFeed,30*60*1000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)loadFeed();});
});